language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
  - gradle -b wrapper.gradle wrapper
  - yes | sdkmanager "platforms;android-28"
after_failure:
  - if [ -f app/build/outputs/lint-results.xml ]; then cat app/build/outputs/lint-results.xml; fi